### ISSUE TITLE
LSS notebook on tutorials/Dec2020

### ISSUE THREAD

**Issue by forero** [desihub/LSS#33]
Hi @ashleyjross: I am checking that all the notebooks in the tutorials repo work with kernel 22.2. 

I was working with the LSS notebook under `tutorials/Dec2020` and found that there is a missing file : `/project/projectdirs/desi/users/ajross/dr9/LRGtargetDR9m44.fits`. Is there a way for me to produce that file or should I wait for you to produce it?

Here is the current status of that notebook
https://github.com/desihub/tutorials/blob/c4afc5c7552fdc6676d81a7e4b5c8f322d508c47/Dec2020/LSS.ipynb

Thanks!

**Comment by ashleyjross** [comment]
This is super-old, so I just copied the LRGtargetDR9m42.fits (which did exist) to LRGtargetDR9m44.fits. The numbers are supposed to correspond to the verson of the targeting, but I can't imagine any major problems from doing this just to get the notebook to work.

From: Jaime Forero-Romero ***@***.***>
Date: Tuesday, May 10, 2022 at 12:28 PM
To: desihub/LSS ***@***.***>
Cc: ashleyjross ***@***.***>, Mention ***@***.***>
Subject: [desihub/LSS] LSS notebook on tutorials/Dec2020 (Issue #33)

Hi @ashleyjross<https://github.com/ashleyjross>: I am checking that all the notebooks in the tutorials repo work with kernel 22.2.

I was working with the LSS notebook under tutorials/Dec2020 and found that there is a missing file : /project/projectdirs/desi/users/ajross/dr9/LRGtargetDR9m44.fits. Is there a way for me to produce that file or should I wait for you to produce it?

Here is the current status of that notebook
https://github.com/desihub/tutorials/blob/c4afc5c7552fdc6676d81a7e4b5c8f322d508c47/Dec2020/LSS.ipynb

Thanks!

**Comment by forero** [comment]
Wonderful. Thanks!

**Comment by sbailey** [comment]
@forero (and any others making tutorial updates), while you are making changes, please start using '/global/cfs/cdirs/desi' instead of '/project/projectdirs/desi'.  On cori those are the same, but perlmutter won't have the old `/project/projectdirs -> /global/cfs/cdirs' symlink.

Even better would be to use $DESI_ROOT as the prefix to make the tutorials slightly more portable.  The comments could mention that $DESI_ROOT=/global/cfs/cdirs/desi at NERSC.
