### ISSUE TITLE
Useful to add the arguments for the output filename and "overwrite" option?

### ISSUE THREAD

**Issue by zdplayground** [desihub/LSS#39]
https://github.com/desihub/LSS/blob/3ded0e3841b7865cc1d67a1396351b6627855a75/py/LSS/bitweights.py#L162

Just a suggestion:
When I use some code calling this function, the output filename is fixed, and there is no option to overwrite the output.
When we do some tests calling this function many times, it is not very convenient, since we need to rename or remove the output before calling this function again.

best,
Zhejie Ding

**Comment by ashleyjross** [comment]
I agree that would definitely be an improvement. Do you want to try to make the changes and submit a PR?

From: Zhejie Ding ***@***.***>
Date: Friday, June 3, 2022 at 11:44 PM
To: desihub/LSS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [desihub/LSS] Useful to add the arguments for the output filename and "overwrite" option? (Issue #39)

https://github.com/desihub/LSS/blob/3ded0e3841b7865cc1d67a1396351b6627855a75/py/LSS/bitweights.py#L162

Just a suggestion:
When I use some code calling this function, the output filename is fixed, and there is no option to overwrite the output.
When we do some tests calling this function many times, it is not very convenient, since we need to rename or remove the output before calling this function again.

best,
Zhejie Ding

**Comment by ashleyjross** [comment]
(I believe Zhejie did as suggested.)
