### ISSUE TITLE
TILES entry is not correct for some targets in the clustering catalogs

### ISSUE THREAD

**Issue by moustakas** [desihub/LSS#56]
Compare:
```
import fitsio
from astropy.table import Table
cat = Table(fitsio.read('/global/cfs/cdirs/desi/survey/catalogs/edav1/sv3/LSScats/clustering/ELGnotqso_N_clustering.dat.fits'))
cat[cat['TARGETID'] == 39633390168703205]['TILES']
<Column name='TILES' dtype='str51' length=1>
92-452
```
with
```
fm = Table(fitsio.read('/global/cfs/cdirs/desi/spectro/redux/fuji/healpix/sv3/dark/112/11215/redrock-sv3-dark-11215.fits', 'EXP_FIBERMAP'))
fm[fm['TARGETID'] == 39633390168703205]['TILEID']
<Column name='TILEID' dtype='int32' length=4>
 83
452
452
452
```
I discovered this because `FastSpecFit` stores a similar quantity and for this target my catalog listed 83 and 452.

**Comment by ashleyjross** [comment]
Thanks for looking at this, these kinds of checks are really good, both for final validation and for documentation! It turns out this is not a bug (phew!), though I definitely thought it was when I first read everything. Details below:

TILES is meant to track the tiles where a target could have had a good observation. This means tracking all of the times something shows up in POTENTIAL_ASSIGNMENTS and masking the times that were "bad hardware". The information for SV3 dark time is contained in /global/cfs/cdirs/desi/survey/catalogs/edav1/sv3/inputs_wspec/data/datcomb_dark_tarspecwdup_Alltiles.fits and has also been matched (based on TARGETID, TILEID, LOCATION) to the per tile redshift file.

For this target, the TILEID in that file are
452,  83,  92

So, it was a potential assignment on three tiles. Why does TILES only have 92 and 452? That is because 83 was a "bad" observation. For SV3, we just use COADD_FIBERSTATUS != 0 to denote a bad observation. (This is imperfect and for the main survey we use the same criteria as MTL decisions plus the possibility of a post-facto TILEID+LOCATION veto mask.)

In order to track the TILEID+LOCATION, we have a column TILELOCID (10000*TILEID+LOCATION). The TILELOCID for this target on tile 83 is 830526 (so it was at LOCATION 526). Selecting on that TILELOCID, there were two potential assignments. The unobserved one has COADD_FIBERSTATUS = 999999 (this should be the case for all of the unobserved entries in that file) and the observed one has COADD_FIBERSTATUS = 8. So, as far as the LSS code is concerned, this TILELOCID gets masked from all subsequent analysis (importantly, for both data and random, but the same random point at a different TILELOCID can be kept just like this target was eventually observed and kept). This includes the counting/tracking of TILEID and hence TILES just has the two entries.

Cross-checking against the redshift file (by selecting TILEID == 83 and LOCATION == 526), the COADD_FIBERSTATUS is indeed 8, so all appears good.
