### ISSUE TITLE
DESI NERSC Environment command

### ISSUE THREAD

**Issue by mcdemart** [desihub/LSS#57]
Minor documentation issue but it left me troubleshooting for a bit.  The command to source the DESI environment on NERSC in the README file here is wrong.  The correct command I believe should be " source /global/common/software/desi/users/adematti/cosmodesi_environment.sh main ".

**Comment by ashleyjross** [comment]
Thanks, I updated the readme. The issue is that there are actually two software development bases, desihub and cosmodesi. The LSS code requires pieces from both, depending on what is being run. So, to get everything working, you need to source both
source /global/common/software/desi/desi_environment.sh main
source /global/common/software/desi/users/adematti/cosmodesi_environment.sh main

Sourcing them in that order seems to work without conflict. (A lot of applications only require one or the other though.)

**Comment by mcdemart** [comment]
OK, thank you for the clarification!

Best,
Matt
